name: issues-translator

on:
  workflow_dispatch:
  issue_comment:
    types: [ created ]
  issues:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: usthe/issues-translate-action@v2.7
        with:
          IS_MODIFY_TITLE: true
