name: lint markdown

on: [push, pull_request]

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lint-md-github-action
        uses: lint-md/github-action@v0.1.1
        with:
          configFile: .lintmdrc
          failOnWarnings: false
          files: ./ ./.github/ ./docs/
