name: lint markdown

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set node version
        uses: actions/setup-node@v5

      - name: Install lint-md
        run: npm install -g @lint-md/cli

      - name: Lint markdown
        run: lint-md --config .lintmdrc --suppress-warnings *.md .github/ docs/
