name: rector

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - '.github/**.yml'
      - '.github/**.yaml'
      - '*.xml'
      - '*.xml.dist'

jobs:
  rector:
    name: rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install --no-interaction --prefer-dist --ansi -v

      - name: Run rector
        run: composer rector-dry-run
