name: secrets check

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          # path: ./
          # base: ${{ github.event.repository.default_branch }}
          # head: ${{ github.ref_name }}
          # extra_args: --results=verified,unknown --only-verified --debug
          extra_args: --results=verified,unknown
